name: todo_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sqflite: ^1.3.0
  intl: ^0.17.0
  flutter_bloc: ^7.1.0
  bloc: ^7.1.0
  conditional_builder: ^1.0.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#   assets:
#     - images/a_dot_burr.jpeg
#     - images/a_dot_ham.jpeg
